"""Auxiliary, non-official views; never replaces or edits evaluate_v2.

Identity normalization ignores identifier/name casing, but NOT value casing
(m and M are different prefixes). Only reference components explicitly marked
unidentified (``∅<number>`` or ``__unresolved_...``) receive spatial ID relief.
The geometry view deliberately ignores identities and values to isolate physical
localization/connectivity. It must not be presented as recognized pin identity.
All assignments are one-to-one. Inputs are not mutated; this module reads no data.
"""
from __future__ import annotations

from collections import Counter
import math
import re

import evaluate_v2 as strict
from pcb.assignment import maximum_weight_assignment

COMPONENT_TOLERANCE = 20.0
PIN_TOLERANCE = 5.0
_UNIDENTIFIED = re.compile(r"^(?:∅\d+|__unresolved(?:_.*)?)$", re.IGNORECASE)
_TEMPORARY_PIN = re.compile(r"^(?:__tmp(?:_|$)|__unresolved(?:_|$)|unk(?:\d|_|$))", re.IGNORECASE)


def _fold(value):
    return value.casefold() if isinstance(value, str) else value


def _kind(component):
    return _fold(component.get("type"))


def _unknown_component(key):
    return bool(_UNIDENTIFIED.fullmatch(key))


def _suffix(key):
    return key[4:] if key[:4].casefold() == "pin_" else key


def _temporary_pin(key):
    return bool(_TEMPORARY_PIN.match(_suffix(key)))


def _name_matches(pred_key, pred, gt_key, gt):
    if _fold(pred.get("Name")) == _fold(gt.get("Name")):
        return True

    def placeholder(name, key):
        return name is None or name == "" or _fold(name) == _fold(key)

    # Export sometimes copies an autogenerated key into Name. Exempt only
    # those copies, never a disagreement between visible chip/model names.
    return _unknown_component(gt_key) and placeholder(pred.get("Name"), pred_key) and \
        placeholder(gt.get("Name"), gt_key)


def _assign(pred_keys, gt_keys, cost):
    """Maximum cardinality first, then minimum bounded cost (0..1)."""
    if not pred_keys or not gt_keys:
        return {}
    cardinality_bonus = min(len(pred_keys), len(gt_keys)) + 1.0
    weights = []
    for pk in pred_keys:
        row = []
        for gk in gt_keys:
            value = cost(pk, gk)
            row.append(0.0 if value is None else cardinality_bonus - min(1.0, max(0.0, value)))
        weights.append(row)
    return {pred_keys[i]: gt_keys[j] for i, j in maximum_weight_assignment(weights) if weights[i][j] > 0}


def _component_maps(pred, gt):
    def spatial(pk, gk, typed=True):
        if typed and _kind(pred[pk]) != _kind(gt[gk]):
            return None
        distance = strict.bbox_error(pred[pk]["bbox"], gt[gk]["bbox"])
        return distance / COMPONENT_TOLERANCE if distance <= COMPONENT_TOLERANCE else None

    pkeys, gkeys = list(pred), list(gt)
    geometry = _assign(pkeys, gkeys, spatial)
    visible_p = [k for k in pkeys if _kind(pred[k]) != "gnd" and not _unknown_component(k)]
    visible_g = [k for k in gkeys if _kind(gt[k]) != "gnd" and not _unknown_component(k)]

    def identity_cost(pk, gk):
        if _fold(pk) != _fold(gk):
            return None
        distance = strict.bbox_error(pred[pk]["bbox"], gt[gk]["bbox"])
        return distance / (1.0 + distance)

    identity = _assign(visible_p, visible_g, identity_cost)
    # GND serial numbers carry no meaning, as in the existing strict evaluator.
    identity.update(_assign([k for k in pkeys if _kind(pred[k]) == "gnd"],
                            [k for k in gkeys if _kind(gt[k]) == "gnd"], spatial))
    remaining_p = [k for k in pkeys if k not in identity]
    used_g = set(identity.values())
    unspecified_g = [k for k in gkeys if k not in used_g and _unknown_component(k)]
    identity.update(_assign(remaining_p, unspecified_g, spatial))
    # Untyped proximity is only an error diagnostic, not a scoring assignment.
    proximity = _assign(pkeys, gkeys, lambda pk, gk: spatial(pk, gk, False))
    return identity, geometry, proximity


def _pin_maps(pred, gt, component_map, *, geometry=False):
    result = {}
    for pk, gk in component_map.items():
        pp, gp = pred.get(pk, {}), gt.get(gk, {})

        def cost(pn, gn):
            if not geometry and (_temporary_pin(pn) or _temporary_pin(gn) or
                                 _fold(_suffix(pn)) != _fold(_suffix(gn))):
                return None
            distance = math.dist(strict.point(pp[pn]["point"]), strict.point(gp[gn]["point"]))
            if geometry:
                return distance / PIN_TOLERANCE if distance <= PIN_TOLERANCE else None
            return distance / (1.0 + distance)

        result.update({(pk, pn): (gk, gn) for pn, gn in _assign(list(pp), list(gp), cost).items()})
    return result


def _reference_lookup(data):
    return {f"{ck}.{_suffix(pk)}": (ck, pk) for ck, pins in data["pins"].items() for pk in pins}


def _net_sets(pred, gt, pin_map):
    plookup, glookup = _reference_lookup(pred), _reference_lookup(gt)

    def reference(ref, lookup, predicted):
        pin = lookup.get(ref)
        if predicted:
            matched = pin_map.get(pin)
            return ("gt", *matched) if matched is not None else ("unmatched_prediction", ref)
        return ("gt", *pin) if pin is not None else ("unknown_reference", ref)

    ps = [{reference(r, plookup, True) for r in strict.net_members(n)} for n in pred["nets"].values()]
    gs = [{reference(r, glookup, False) for r in strict.net_members(n)} for n in gt["nets"].values()]
    return ps, gs


def _observable_pin(component_key, pin_key, pin, components):
    # Prefix/type spelling is also case-insensitive in the auxiliary view.
    component = components[component_key]
    normalized = {component_key: {**component, "type": _kind(component)}}
    return strict.observable_pin(component_key, "pin_" + _suffix(pin_key), pin, normalized)


def _score(pred, gt, component_map, pin_map, diagnostics, *, geometry=False):
    pc, gc = pred["components"], gt["components"]
    pp, gp = pred["pins"], gt["pins"]

    def good_component(pk, gk):
        p, g = pc[pk], gc[gk]
        if _kind(p) != _kind(g) or strict.bbox_error(p["bbox"], g["bbox"]) > COMPONENT_TOLERANCE:
            return False
        if geometry:
            return True
        if _kind(p) == "box" and not _name_matches(pk, p, gk, g):
            return False
        return _kind(p) not in ("r", "c") or p.get("value") == g.get("value")

    def good_pin(p, g):
        a, b = pp[p[0]][p[1]], gp[g[0]][g[1]]
        return (geometry or _fold(a.get("pinname", "")) == _fold(b.get("pinname", ""))) and \
            math.dist(strict.point(a["point"]), strict.point(b["point"])) <= PIN_TOLERANCE

    component_hits = {(pk, gk) for pk, gk in component_map.items() if good_component(pk, gk)}
    pin_hits = {(pk, gk) for pk, gk in pin_map.items() if good_pin(pk, gk)}
    pcount, gcount = sum(map(len, pp.values())), sum(map(len, gp.values()))
    psets, gsets = _net_sets(pred, gt, pin_map)
    pnets, gnets = list(pred["nets"].values()), list(gt["nets"].values())
    matches = strict.hungarian_pairs(psets, gsets)
    net_hits = sum(len(psets[i] & gsets[j]) for i, j, _ in matches)
    line_hits = sum(strict.segment_match_count(list(pnets[i]["edges"].values()),
                                               list(gnets[j]["edges"].values())) for i, j, _ in matches)
    pairs_p, pairs_g = strict.pair_set(psets), strict.pair_set(gsets)
    metrics = {
        "Component": strict.prf(len(component_hits), len(pc), len(gc)),
        "Pin": strict.prf(len(pin_hits), pcount, gcount),
        "NetHypergraph": strict.prf(net_hits, sum(map(len, psets)), sum(map(len, gsets))),
        "NetLine": strict.prf(line_hits, sum(len(n["edges"]) for n in pnets), sum(len(n["edges"]) for n in gnets)),
        "PinPair": strict.prf(len(pairs_p & pairs_g), len(pairs_p), len(pairs_g)),
    }
    # Preserve the old evaluator's explicitly filtered observable-only view.
    # In particular it is not the primary metric and excludes unmatched net refs.
    gc_observable = {k for k, c in gc.items() if not _unknown_component(k) or _kind(c) == "gnd"}
    pc_observable = {k for k, c in pc.items() if (not _unknown_component(k) or _kind(c) == "gnd") and
                     (k not in component_map or component_map[k] in gc_observable)}
    gp_observable = {(ck, pk) for ck, pins in gp.items() for pk, pin in pins.items()
                     if ck in gc_observable and _observable_pin(ck, pk, pin, gc)}
    pp_observable = {(ck, pk) for ck, pins in pp.items() for pk, pin in pins.items()
                     if ck in pc_observable and _observable_pin(ck, pk, pin, pc)}
    allowed = {("gt", *pin) for pin in gp_observable}
    opsets = [s & allowed for s in psets if s & allowed]
    ogsets = [s & allowed for s in gsets if s & allowed]
    om = strict.hungarian_pairs(opsets, ogsets)
    opp, opg = strict.pair_set(opsets), strict.pair_set(ogsets)
    observable = {
        "Component": strict.prf(sum(p in pc_observable and g in gc_observable for p, g in component_hits),
                                len(pc_observable), len(gc_observable)),
        "Pin": strict.prf(sum(p in pp_observable and g in gp_observable for p, g in pin_hits),
                          len(pp_observable), len(gp_observable)),
        "NetHypergraph": strict.prf(sum(len(opsets[i] & ogsets[j]) for i, j, _ in om),
                                    sum(map(len, opsets)), sum(map(len, ogsets))),
        "PinPair": strict.prf(len(opp & opg), len(opp), len(opg)),
    }
    counts = {
        "pred_component_count": len(pc), "gt_component_count": len(gc),
        "pred_pin_count": pcount, "gt_pin_count": gcount,
        "pred_net_count": len(pnets), "gt_net_count": len(gnets),
        "pred_edge_count": metrics["NetLine"]["pred"], "gt_edge_count": metrics["NetLine"]["gt"],
        "singleton_net_count": sum(len(s) == 1 for s in psets),
        "empty_edge_net_count": sum(not n["edges"] for n in pnets),
        "unattached_pin_count": len(diagnostics.get("unattached_pins", [])),
        "runtime": float(diagnostics.get("seconds", 0)),
    }
    score = 100 * sum(weight * metrics[name]["f1"] for name, weight in
                      (("Component", .30), ("Pin", .25), ("NetHypergraph", .35), ("NetLine", .10)))
    return {"metrics": metrics, "observable_only": observable, "FinalScore": score,
            "counts": counts, "component_key_matches": len(component_map)}


def _case_collisions(keys):
    groups = Counter(_fold(key) for key in keys)
    return sum(n - 1 for n in groups.values() if n > 1)


def evaluate_case(pred, gt, diagnostics=None):
    """Return two aggregate-compatible auxiliary views and non-causal errors.

    Error categories can overlap: a wrong type may also leave a typed spatial
    match absent. They are observations, not a claim that OCR caused the error.
    No dataset loading occurs here; callers must enforce the case whitelist.
    """
    diagnostics = diagnostics or {}
    identity_components, geometry_components, proximity = _component_maps(pred["components"], gt["components"])
    identity_pins = _pin_maps(pred["pins"], gt["pins"], identity_components)
    geometry_pins = _pin_maps(pred["pins"], gt["pins"], geometry_components, geometry=True)
    identity = _score(pred, gt, identity_components, identity_pins, diagnostics)
    geometry = _score(pred, gt, geometry_components, geometry_pins, diagnostics, geometry=True)
    pc, gc, pp, gp = pred["components"], gt["components"], pred["pins"], gt["pins"]
    value_pairs = [(pc[p], gc[g]) for p, g in geometry_components.items() if _kind(pc[p]) in ("r", "c")]
    name_pairs = [(p, g) for p, g in geometry_components.items() if _kind(pc[p]) == "box"]
    pin_pairs = [(p, g, pp[p[0]][p[1]], gp[g[0]][g[1]]) for p, g in geometry_pins.items()]
    errors = {
        "categories_overlap": True,
        "causal_ocr_attribution": False,
        "components": {
            "typed_bbox_matches": len(geometry_components),
            "gt_without_typed_bbox_match": len(gc) - len(geometry_components),
            "pred_without_typed_bbox_match": len(pc) - len(geometry_components),
            "wrong_visible_identifier_on_typed_bbox_match": sum(
                not _unknown_component(g) and _kind(gc[g]) != "gnd" and _fold(p) != _fold(g)
                for p, g in geometry_components.items()),
            "unlabeled_reference_identifier_exemptions": sum(_unknown_component(g) for g in identity_components.values()),
            "bbox_error_on_identity_match": sum(strict.bbox_error(pc[p]["bbox"], gc[g]["bbox"]) > COMPONENT_TOLERANCE
                                                 for p, g in identity_components.items()),
            "type_error_on_identity_match": sum(_kind(pc[p]) != _kind(gc[g]) for p, g in identity_components.items()),
            "different_type_on_untyped_bbox_match": sum(_kind(pc[p]) != _kind(gc[g]) for p, g in proximity.items()),
            "value_mismatch_on_typed_bbox_match": sum(p.get("value") != g.get("value") for p, g in value_pairs),
            "box_name_mismatch_on_typed_bbox_match": sum(not _name_matches(p, pc[p], g, gc[g]) for p, g in name_pairs),
            "pred_casefold_key_collisions": _case_collisions(pc),
            "gt_casefold_key_collisions": _case_collisions(gc),
        },
        "pins": {
            "typed_component_and_point_matches": len(geometry_pins),
            "gt_without_typed_component_and_point_match": sum(map(len, gp.values())) - len(geometry_pins),
            "pred_without_typed_component_and_point_match": sum(map(len, pp.values())) - len(geometry_pins),
            "wrong_number_on_point_match": sum(not _temporary_pin(p[1]) and _fold(_suffix(p[1])) != _fold(_suffix(g[1]))
                                                for p, g, _, _ in pin_pairs),
            "temporary_number_on_point_match": sum(_temporary_pin(p[1]) for p, _, _, _ in pin_pairs),
            "name_mismatch_on_point_match": sum(_fold(a.get("pinname", "")) != _fold(b.get("pinname", ""))
                                                for _, _, a, b in pin_pairs),
            "point_error_on_identity_match": sum(math.dist(strict.point(pp[p[0]][p[1]]["point"]),
                                                            strict.point(gp[g[0]][g[1]]["point"])) > PIN_TOLERANCE
                                                  for p, g in identity_pins.items()),
            "pred_casefold_key_collisions": sum(_case_collisions(_suffix(k) for k in pins) for pins in pp.values()),
            "gt_casefold_key_collisions": sum(_case_collisions(_suffix(k) for k in pins) for pins in gp.values()),
        },
        "connectivity": {
            f"{view}_{label}": result["metrics"]["PinPair"][count] - result["metrics"]["PinPair"]["tp"]
            for view, result in (("identity", identity), ("geometry", geometry))
            for label, count in (("missing_pin_pairs", "gt"), ("extra_pin_pairs", "pred"))
        },
    }

    def matching(cm, pm):
        return {"components": cm, "pins": {f"{p[0]}.{_suffix(p[1])}": f"{g[0]}.{_suffix(g[1])}" for p, g in pm.items()}}

    return {
        "identity_normalized": identity,
        "geometry_connectivity": geometry,
        "error_breakdown": errors,
        "matching": {"identity_normalized": matching(identity_components, identity_pins),
                     "geometry_connectivity": matching(geometry_components, geometry_pins)},
    }
